on: push
jobs:
  code-coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [13, 14]
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Check Code Coverage
        continue-on-error: true
        run: npm run coverage

      - name: Archive Test Result
        uses: actions/upload-artifact@v7
        with:
          name: Code-Coverage-Result
          path: coverage
          retention-days: 5